sudo: required

language: go

go:
  - 1.3
  
services:
  - docker

before_install:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - git submodule init
  - git submodule update
  - go get -u -v github.com/spf13/hugo

script:
  - hugo -t casper
  - docker build -t debonairio/website:latest .
  - docker push debonairio/website:latest
