baseurl = "http://www.debonair.io/"
languageCode = "en-us"
title = "Debonair.io"
DisqusShortname = "debonairio"

[params]
  description = "Classy code, debonair developers, inspiring infrastructure, and stylish stacks."
  hideHUGOSupport = true
